#!/usr/bin/python3

from pwn import *
import sys
import time
from checkType import checkTypeCSV, checkTypeJson
from util import usage, curr_time_taken
from payloads import *
from checkType import *

# number of processes to start
N_ITER = 10
# length of overflows, cyclics, etc.
LEN = 100

if __name__ == '__main__':

    # Check valid input
    if len(sys.argv) != 3:
        usage()

    # If valid, then check given input file, open for reading
    try: 
        sample_file = open(sys.argv[2], 'r')

    except:
        print(f"Error: Cannot open .txt file")
        usage()
        sys.exit(1)
        
    init_time = time.time()
    binary_file = sys.argv[1]
    sample_file_str = sys.argv[2]

    print(f'AAAAAAAAfuzzing {binary_file}')

    if checkTypeJson(sample_file):
        log.info("going to assess binary as JSON")
        fuzzy_json(binary_file, sample_file_str)
    
    elif checkTypeCSV(sample_file):  
        log.info("going to assess binary as CSV")
        fuzz_csv(binary_file, sample_file, '/tmp/bad.txt')

    print(f"Fuzzer process done in {curr_time_taken(init_time)} seconds...")

    sys.exit()
